# Similar to ./Dockerfile, but for development purposes (not final stage production build)
FROM node:12.16.1-alpine3.9 as builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --production=false

COPY ./ ./

RUN yarn build

EXPOSE 8080

CMD [ "node", "build/index.js" ]
